services:
  nginx:
    #build nginx from dockerfile config.
    #this case simply bring up a default container from nginx official image.
    build: ./nginx/
    #expose on port 80
    ports:
      - 80:80
    networks:
      - internal
    #mount the app directory (php web contents) to the web root directory of nginx container
    volumes:
      - ./app/:/var/www/html/

  php:
    #build the app container from Dockerfile at .app/docker
    build: ./app/docker/
    expose:
      - 9000
    networks:
      - internal
    #mount the app directory (php web contents) to the web root directory of nginx container
    volumes:
      - ./app/:/var/www/html/
    #adjust owner and permission to the images directory (for image upload)
    command: >
      sh -c "chown www-data:www-data /var/www/html/src/gallery/images &&
      chmod 755 /var/www/html/src/gallery/images &&
      php-fpm"

  db:
    image: mariadb
    volumes:
      #mount the docker managed data_sql as sql volume storage for maria-db.
      - data_sql:/var/lib/mysql
      #executing init script during the initial configuration of the database instance.
      #only run once, if no initial table created in database
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: hotel
#docker-managed volume. data in this could not be shared
volumes:
  data_sql:
networks:
  internal:
    driver: bridge
